### ISSUE TITLE
BB84.md in The Applications Layer needs writing

### ISSUE THREAD

**Issue by QTM3x** [QTM3x/Quantum-Internet#2]
The original paper is in the [file](https://github.com/QTM3x/Quantum-Internet/blob/master/1.%20The%20Applications%20Layer/BB84.md). The steps of the protocol can be found there. We need at least the steps to able to think about how to start implementing it.

**Comment by richwheels** [comment]
Hey, I'm taking the quantum internet course on edx. I'm currently working as an IT contractor but have a masters degree in electronic and communications engineering so wanted to play around with some quantum protocols. This seems like a good opportunity, so if you'd like to assign me to this job then I can research the preferable language, implementation, etc and get started on the BB84 application layer. Thanks, Rich.

**Comment by QTM3x** [comment]
Hi Richwheels, 

Feel free to add rough ideas to this thread before committing to working on any of them. It sounds like your approach might be a little too broad.

**Comment by richwheels** [comment]
Hi QTM3x, 
So I have a few ideas/questions. We are going to want to stick with the OSI layer 7 model so to my understanding, the applications layer will do the following:

1. Store the BB84 protocol code definition
2. Ensure that communications interfaces exist and are operational
3. Encode/decode data from/to BB84 protocol packets
4. Check for errors in decoded data
5. Present the data to the application
6. Some form of authentication, potentially? See question below...

A question that is always on my mind with this is how do we stop Alice from intercepting by some other means after/before the data has been secured in the quantum realm? It feels like a chicken and egg scenario.

If there are any other points I've missed then please add (I'm only using my lunch breaks to work on this so don't have full concentration).

Thanks :)

**Comment by QTM3x** [comment]
Sounds like a good start! I would say let's not write code right now  (may be pseudo-code is fine), and let's focus on describing roughly how the steps above are going to work. We should begin with adding the definition of the BB84 protocol to the BB84.md file.

As for your question:
> A question that is always on my mind with this is how do we stop Alice from intercepting by some other means after/before the data has been secured in the quantum realm? It feels like a chicken and egg scenario.

Let me see if I understand your question correctly. are you asking how the initial authentication will happen, i.e, how Bob will know that Alice really is Alice? If so, then the answer is that they have to share an initial shared secret, clearly. The point of quantum key distribution protocols like BB84 is to create more secret key in a completely secure way.

**Comment by richwheels** [comment]
Sounds good to me. I will work on the .md file over the next few days. I can start the definition file tomorrow lunchtime and work on it further on weekday lunchtimes that follow (I may also be able to spare an hour or two on the weekend but am extremely busy this and next month). It would be nice if someone could work on the same file after I have done the first pull request to add to /edit and then we can iterate between us until happy.

No, really the question is around the idea that we can create the application layer and it will convert do the key generation, probably also makes sense to do encryption using the secure key at the application layer also and then forward to the next layers for transmission. However, I'd like to understand how we can be absolutely positive that Eve is not somehow connected and listening to the system prior to the key generation or at the time of generation. Thus, being able to watch the key generation or worse still, see the data before encryption takes place. I suppose pre-application layer evesdropping, it's almost as if we need the system to generate a key on boot up and then encrypt all activity in the system. It's a little hard to explain via comments but hopefully you understand a little better from this.

**Comment by richwheels** [comment]
One final thing, I have tried pushing an initial commit to the repo and I get 
```> git push origin master:master
remote: Permission to QTM3x/Quantum-Internet.git denied to richwheels.
fatal: unable to access 'https://github.com/QTM3x/Quantum-Internet.git/': The requested URL returned error: 403
```
Do you need to edit permissions your end? I have updated the BB84 file this evening and would like to push those changes before someone else takes a look at it. Thanks!

**Comment by QTM3x** [comment]
> However, I'd like to understand how we can be absolutely positive that Eve is not somehow connected and listening to the system prior to the key generation or at the time of generation. Thus, being able to watch the key generation or worse still, see the data before encryption takes place.

If Eve is directly connected to your computer, standing over your shoulder as you input the data, or otherwise in direct proximity to the unencrypted data, then there is nothing you can do about it. All cryptographic protocols assume that Eve will only try to extract the data after it has been encrypted.

> Do you need to edit permissions your end? I have updated the BB84 file this evening and would like to push those changes before someone else takes a look at it. Thanks!

You need to fork the repository first, then apply the changes to the fork, then create a pull request. Let me know if you need help with this :)

**Comment by richwheels** [comment]
Ok. I will try again at lunch. I am used to azure devops and vscode so don't really use git. The GIT inside azure devops hooks straight into vscode with set up/credentials etc. I'll let you know if I get stuck again. Thanks!

**Comment by AgentANAKIN** [comment]
I read in the file about the parties "historically" being referred to as Alice and Bob and just wanted to make the minor contribution that they were "born" in 1978: http://people.csail.mit.edu/rivest/Rsapaper.pdf

**Comment by BassemSafieldeen** [comment]
Hi @richwheels 

I have made some [modifications](https://github.com/richwheels/Quantum-Internet/pull/1/commits/a4367d7af520f518921328da3b14f36f3cbb468c) to your fork of the repository. Have you had a chance to look at them yet?

**Comment by saum-g** [comment]
Hi,

This is Saumya Goyal from India. I wanted to contribute to the repository. I am thinking starting with this issue, particularly with adding the missing pseudocodes in BB84.md

**Comment by BassemSafieldeen** [comment]
Hi @saum-g ! 

Adding guidelines for writing "quantum pseudocode" is actually a good idea. Feel free to prepare a draft and add it in the Application Layer folder! Then you can update it as you write the pseudocode in the BB84.md file. 

I would suggest keeping it intuitive and simple. For example, may be to say that want to apply a Hadamard gate on qubit q1 you write 

`
Hadamard q1.
`

And to apply  a cnot gate between two qubits A and B you might write 

`
CNOT q1 q2.
`

**Comment by BassemSafieldeen** [comment]
I think this is done.
