### ISSUE TITLE
Quantum capacity of optical fibers

### ISSUE THREAD

**Issue by BassemSafieldeen** [QTM3x/Quantum-Internet#43]
In the quantum internet we are building we use quantum repeaters. We use repeaters instead of just a segment of optical fiber stretched between the end-nodes because we [think](https://arxiv.org/pdf/quant-ph/9803056.pdf) they can increase the rate at which we can share Bell pairs.

When building repeaters, we would like to know if we did it right. To do that, we need to compare the performance of the repeaters to the performance of an optical fiber alone. But we first need to know what the performance of an optical fiber alone is, right? That is, we need to know the answer to this question: If we use an optical fiber alone what is the maximum number of Bell pairs that we can establish between Alice and Bob in, say, an hour? Or, more technically stated: What is the quantum capacity of an optical fiber?

An optical fiber, like any medium through which (quantum) information flows, can be mathematically modelled as a [quantum channel](https://en.wikipedia.org/wiki/Quantum_channel). In particular, an optical fiber can be modelled using a type of channels called **Gaussian bosonic channels** --- see, e.g., the introduction of [this paper](https://arxiv.org/pdf/1312.3545.pdf), or [this paper](https://www.nature.com/articles/ncomms15043.pdf). So if we know the quantum capacity of these channels we know how an optical fiber performs, and then we can check if our repeaters really do better.

This [paper](https://www.nature.com/articles/ncomms15043) seems to contain a precise formula for the quantum capacity of these channels, and, consequently, for our optical fiber. We need someone to read the paper and extract from it this information. I have created the `capacity.ipynb` [notebook](https://github.com/QTM3x/Quantum-Internet/blob/master/_5_The_Physical_Layer/optical_fiber/capacity.ipynb) in the `optical_fiber` package for this. 

In addition to the formula for the capacity (and a bit of explanation of the intuition behind it), if you find something in the paper that you think is clever or nice feel free to explain it in the notebook, too :)

**Comment by BassemSafieldeen** [comment]
Hmm, can someone tell me which of these titles best conveys how cool this issue is?

I think the issue is cool because it opens the door a little wider to quantum Shannon theory, which is a very nice and fundamental research area.

**Comment by Praveen91299** [comment]
> Hmm, can someone tell me which of these titles best conveys how cool this issue is?

I think the current title sounds cool, though I do like the "Theory: Quantum capacity ..." it sounds like some movie title xD
And yeah, capacities is a really cool and exciting field, I still can't get my head around super-additive channels. It's almost like magic!

**Comment by BassemSafieldeen** [comment]
> > Hmm, can someone tell me which of these titles best conveys how cool this issue is?
> 
> I think the current title sounds cool, though I do like the "Theory: Quantum capacity ..." it sounds like some movie title xD

Ok, I'll keep the current title, then. 

> And yeah, capacities is a really cool and exciting field, I still can't get my head around super-additive channels. It's almost like magic!

I think so, too, yes :)

**Comment by BassemSafieldeen** [comment]
@Praveen91299 you can switch to working on this issue if you want, by the way. Anybody can work on any issue, really.

**Comment by Praveen91299** [comment]
Sounds good, I'll working on this.
