### ISSUE TITLE
Latex not rendering in .md files

### ISSUE THREAD

**Issue by QTM3x** [QTM3x/Quantum-Internet#9]
The problem can be seen for example in the BB84.md file. 

One way we can solve this is to move to .ipynb (IPython notebooks) instead of .md files. This will be nice especially that we plan to write code in the future. 

However for now, in order not to scare away people who have not used IPython notebooks before, we are going to stick with the .md files for a little longer.

**Comment by BassemSafieldeen** [comment]
@adityakrgupta25 has patched things up a bit for now by changing the syntax to markdown syntax.

**Comment by BassemSafieldeen** [comment]
Will re-open again later when it becomes more pressing.
